"""init

Revision ID: 04f7fd038b41
Revises: 
Create Date: 2026-05-29 12:32:57.875042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04f7fd038b41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('annot_id', sa.Text(), nullable=False),
    sa.Column('annot_type', sa.Text(), nullable=False),
    sa.Column('annot_data', sa.Text(), nullable=False),
    sa.Column('searchable_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book', 'user_type', 'user', 'format', 'annot_type', 'annot_id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index('annot_idx', ['book'], unique=False)

    op.create_table('annotations_dirtied',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book')
    )
    op.create_table('annotations_fts',
    sa.Column('searchable_text', sa.Text(), nullable=True)
    )
    op.create_table('annotations_fts_config',
    sa.Column('k', sa.Text(), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('annotations_fts_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations_fts_docsize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sz', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations_fts_idx',
    sa.Column('segid', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('pgno', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('annotations_fts_stemmed',
    sa.Column('searchable_text', sa.Text(), nullable=True)
    )
    op.create_table('annotations_fts_stemmed_config',
    sa.Column('k', sa.Text(), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('annotations_fts_stemmed_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations_fts_stemmed_docsize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sz', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations_fts_stemmed_idx',
    sa.Column('segid', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('pgno', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aws_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aws_access_key_id', sa.Text(), nullable=False),
    sa.Column('aws_secret_access_key', sa.Text(), nullable=False),
    sa.Column('default_region', sa.String(length=64), nullable=False),
    sa.Column('default_output_format', sa.String(length=16), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sort', sa.String(), nullable=True),
    sa.Column('author_sort', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('pubdate', sa.TIMESTAMP(), nullable=True),
    sa.Column('series_index', sa.String(), nullable=False),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('has_cover', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_plugin_data',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('val', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book', 'name')
    )
    op.create_table('conversion_options',
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format', 'book')
    )
    with op.batch_alter_table('conversion_options', schema=None) as batch_op:
        batch_op.create_index('conversion_options_idx_a', ['format'], unique=False)
        batch_op.create_index('conversion_options_idx_b', ['book'], unique=False)

    op.create_table('custom_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datatype', sa.String(), nullable=True),
    sa.Column('mark_for_delete', sa.Boolean(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=True),
    sa.Column('normalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('flask_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flask_session_key', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lang_code')
    )
    op.create_table('last_read_positions',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('device', sa.Text(), nullable=False),
    sa.Column('cfi', sa.Text(), nullable=False),
    sa.Column('epoch', sa.Float(), nullable=False),
    sa.Column('pos_frac', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'device', 'book', 'format')
    )
    with op.batch_alter_table('last_read_positions', schema=None) as batch_op:
        batch_op.create_index('lrp_idx', ['book'], unique=False)

    op.create_table('library_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauthProvider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('oauth_client_id', sa.String(), nullable=True),
    sa.Column('oauth_client_secret', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('val', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('allow', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_server', sa.String(), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_ssl', sa.SmallInteger(), nullable=True),
    sa.Column('mail_login', sa.String(), nullable=True),
    sa.Column('mail_password_e', sa.String(), nullable=True),
    sa.Column('mail_password', sa.String(), nullable=True),
    sa.Column('mail_from', sa.String(), nullable=True),
    sa.Column('mail_size', sa.Integer(), nullable=True),
    sa.Column('mail_server_type', sa.SmallInteger(), nullable=True),
    sa.Column('mail_gmail_token', sa.JSON(), nullable=True),
    sa.Column('config_calibre_dir', sa.String(), nullable=True),
    sa.Column('config_calibre_uuid', sa.String(), nullable=True),
    sa.Column('config_calibre_split', sa.Boolean(), nullable=True),
    sa.Column('config_calibre_split_dir', sa.String(), nullable=True),
    sa.Column('config_port', sa.Integer(), nullable=True),
    sa.Column('config_external_port', sa.Integer(), nullable=True),
    sa.Column('config_certfile', sa.String(), nullable=True),
    sa.Column('config_keyfile', sa.String(), nullable=True),
    sa.Column('config_trustedhosts', sa.String(), nullable=True),
    sa.Column('config_calibre_web_title', sa.String(), nullable=True),
    sa.Column('config_books_per_page', sa.Integer(), nullable=True),
    sa.Column('config_random_books', sa.Integer(), nullable=True),
    sa.Column('config_authors_max', sa.Integer(), nullable=True),
    sa.Column('config_read_column', sa.Integer(), nullable=True),
    sa.Column('config_title_regex', sa.String(), nullable=True),
    sa.Column('config_theme', sa.Integer(), nullable=True),
    sa.Column('config_log_level', sa.SmallInteger(), nullable=True),
    sa.Column('config_logfile', sa.String(), nullable=True),
    sa.Column('config_access_log', sa.SmallInteger(), nullable=True),
    sa.Column('config_access_logfile', sa.String(), nullable=True),
    sa.Column('config_uploading', sa.SmallInteger(), nullable=True),
    sa.Column('config_anonbrowse', sa.SmallInteger(), nullable=True),
    sa.Column('config_public_reg', sa.SmallInteger(), nullable=True),
    sa.Column('config_remote_login', sa.Boolean(), nullable=True),
    sa.Column('config_kobo_sync', sa.Boolean(), nullable=True),
    sa.Column('config_default_role', sa.SmallInteger(), nullable=True),
    sa.Column('config_default_show', sa.Integer(), nullable=True),
    sa.Column('config_default_language', sa.String(length=3), nullable=True),
    sa.Column('config_default_locale', sa.String(length=2), nullable=True),
    sa.Column('config_columns_to_ignore', sa.String(), nullable=True),
    sa.Column('config_denied_tags', sa.String(), nullable=True),
    sa.Column('config_allowed_tags', sa.String(), nullable=True),
    sa.Column('config_restricted_column', sa.SmallInteger(), nullable=True),
    sa.Column('config_denied_column_value', sa.String(), nullable=True),
    sa.Column('config_allowed_column_value', sa.String(), nullable=True),
    sa.Column('config_use_goodreads', sa.Boolean(), nullable=True),
    sa.Column('config_goodreads_api_key', sa.String(), nullable=True),
    sa.Column('config_register_email', sa.Boolean(), nullable=True),
    sa.Column('config_login_type', sa.Integer(), nullable=True),
    sa.Column('config_kobo_proxy', sa.Boolean(), nullable=True),
    sa.Column('config_ldap_provider_url', sa.String(), nullable=True),
    sa.Column('config_ldap_port', sa.SmallInteger(), nullable=True),
    sa.Column('config_ldap_authentication', sa.SmallInteger(), nullable=True),
    sa.Column('config_ldap_serv_username', sa.String(), nullable=True),
    sa.Column('config_ldap_serv_password_e', sa.String(), nullable=True),
    sa.Column('config_ldap_serv_password', sa.String(), nullable=True),
    sa.Column('config_ldap_encryption', sa.SmallInteger(), nullable=True),
    sa.Column('config_ldap_cacert_path', sa.String(), nullable=True),
    sa.Column('config_ldap_cert_path', sa.String(), nullable=True),
    sa.Column('config_ldap_key_path', sa.String(), nullable=True),
    sa.Column('config_ldap_dn', sa.String(), nullable=True),
    sa.Column('config_ldap_user_object', sa.String(), nullable=True),
    sa.Column('config_ldap_member_user_object', sa.String(), nullable=True),
    sa.Column('config_ldap_openldap', sa.Boolean(), nullable=True),
    sa.Column('config_ldap_group_object_filter', sa.String(), nullable=True),
    sa.Column('config_ldap_group_members_field', sa.String(), nullable=True),
    sa.Column('config_ldap_group_name', sa.String(), nullable=True),
    sa.Column('config_kepubifypath', sa.String(), nullable=True),
    sa.Column('config_converterpath', sa.String(), nullable=True),
    sa.Column('config_binariesdir', sa.String(), nullable=True),
    sa.Column('config_calibre', sa.String(), nullable=True),
    sa.Column('config_rarfile_location', sa.String(), nullable=True),
    sa.Column('config_upload_formats', sa.String(), nullable=True),
    sa.Column('config_unicode_filename', sa.Boolean(), nullable=True),
    sa.Column('config_embed_metadata', sa.Boolean(), nullable=True),
    sa.Column('config_updatechannel', sa.Integer(), nullable=True),
    sa.Column('config_reverse_proxy_login_header_name', sa.String(), nullable=True),
    sa.Column('config_allow_reverse_proxy_header_login', sa.Boolean(), nullable=True),
    sa.Column('schedule_start_time', sa.Integer(), nullable=True),
    sa.Column('schedule_duration', sa.Integer(), nullable=True),
    sa.Column('schedule_generate_book_covers', sa.Boolean(), nullable=True),
    sa.Column('schedule_generate_series_covers', sa.Boolean(), nullable=True),
    sa.Column('schedule_reconnect', sa.Boolean(), nullable=True),
    sa.Column('schedule_metadata_backup', sa.Boolean(), nullable=True),
    sa.Column('config_password_policy', sa.Boolean(), nullable=True),
    sa.Column('config_password_min_length', sa.Integer(), nullable=True),
    sa.Column('config_password_number', sa.Boolean(), nullable=True),
    sa.Column('config_password_lower', sa.Boolean(), nullable=True),
    sa.Column('config_password_upper', sa.Boolean(), nullable=True),
    sa.Column('config_password_character', sa.Boolean(), nullable=True),
    sa.Column('config_password_special', sa.Boolean(), nullable=True),
    sa.Column('config_session', sa.Integer(), nullable=True),
    sa.Column('config_ratelimiter', sa.Boolean(), nullable=True),
    sa.Column('config_limiter_uri', sa.String(), nullable=True),
    sa.Column('config_limiter_options', sa.String(), nullable=True),
    sa.Column('config_check_extensions', sa.Boolean(), nullable=True),
    sa.Column('config_db_host', sa.String(), nullable=True),
    sa.Column('config_db_port', sa.String(), nullable=True),
    sa.Column('config_db_name', sa.String(), nullable=True),
    sa.Column('config_db_user', sa.String(), nullable=True),
    sa.Column('config_db_password_e', sa.String(), nullable=True),
    sa.Column('config_db_password', sa.String(), nullable=True),
    sa.Column('config_database_url', sa.String(), nullable=True),
    sa.Column('config_use_postgresql', sa.Boolean(), nullable=True),
    sa.Column('config_use_postgresql_metadata', sa.Boolean(), nullable=True),
    sa.Column('config_postgresql_metadata_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sso_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sso_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sso_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sso_users_google_id'), ['google_id'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('resolution', sa.SmallInteger(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('kindle_mail', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=True),
    sa.Column('sidebar_view', sa.Integer(), nullable=True),
    sa.Column('default_language', sa.String(length=3), nullable=True),
    sa.Column('denied_tags', sa.String(), nullable=True),
    sa.Column('allowed_tags', sa.String(), nullable=True),
    sa.Column('denied_column_value', sa.String(), nullable=True),
    sa.Column('allowed_column_value', sa.String(), nullable=True),
    sa.Column('view_settings', sa.JSON(), nullable=True),
    sa.Column('kobo_only_shelves_sync', sa.Integer(), nullable=True),
    sa.Column('forum_avatar', sa.String(length=150), nullable=True),
    sa.Column('forum_email_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('archived_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_read_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('read_status', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_time_started_reading', sa.DateTime(), nullable=True),
    sa.Column('times_started_reading', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('bookmark_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_authors_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book', 'author')
    )
    op.create_table('books_languages_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['lang_code'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('book', 'lang_code')
    )
    op.create_table('books_pages_link',
    sa.Column('pages', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('algorithm', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('format', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('format_size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('needs_scan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('link_timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book')
    )
    with op.batch_alter_table('books_pages_link', schema=None) as batch_op:
        batch_op.create_index('books_pages_link_pidx', ['needs_scan'], unique=False)

    op.create_table('books_publishers_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('book', 'publisher')
    )
    op.create_table('books_ratings_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['rating'], ['ratings.id'], ),
    sa.PrimaryKeyConstraint('book', 'rating')
    )
    op.create_table('books_series_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('book', 'series')
    )
    op.create_table('books_tags_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('book', 'tag')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('uncompressed_size', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('val', sa.String(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_reading_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('priority_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_synced_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_dirtied',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book')
    )
    op.create_table('oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remote_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kobo_sync', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelf_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_key', sa.String(), nullable=True),
    sa.Column('random', sa.String(), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_shelf_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('shelf', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shelf'], ['shelf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_reading_state_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('location_source', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('location_value', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('content_source_progress_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['kobo_reading_state_id'], ['kobo_reading_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kobo_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kobo_reading_state_id', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('remaining_time_minutes', sa.Integer(), nullable=True),
    sa.Column('spent_reading_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kobo_reading_state_id'], ['kobo_reading_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kobo_statistics')
    op.drop_table('kobo_bookmark')
    op.drop_table('book_shelf_link')
    op.drop_table('user_session')
    op.drop_table('shelf_archive')
    op.drop_table('shelf')
    op.drop_table('remote_auth_token')
    op.drop_table('oauth')
    op.drop_table('metadata_dirtied')
    op.drop_table('kobo_synced_books')
    op.drop_table('kobo_reading_state')
    op.drop_table('identifiers')
    op.drop_table('downloads')
    op.drop_table('data')
    op.drop_table('comments')
    op.drop_table('books_tags_link')
    op.drop_table('books_series_link')
    op.drop_table('books_ratings_link')
    op.drop_table('books_publishers_link')
    with op.batch_alter_table('books_pages_link', schema=None) as batch_op:
        batch_op.drop_index('books_pages_link_pidx')

    op.drop_table('books_pages_link')
    op.drop_table('books_languages_link')
    op.drop_table('books_authors_link')
    op.drop_table('bookmark')
    op.drop_table('book_read_link')
    op.drop_table('archived_book')
    op.drop_table('users')
    op.drop_table('thumbnail')
    op.drop_table('tags')
    with op.batch_alter_table('sso_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sso_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_sso_users_email'))

    op.drop_table('sso_users')
    op.drop_table('settings')
    op.drop_table('series')
    op.drop_table('registration')
    op.drop_table('ratings')
    op.drop_table('publishers')
    op.drop_table('preferences')
    op.drop_table('oauthProvider')
    op.drop_table('library_id')
    with op.batch_alter_table('last_read_positions', schema=None) as batch_op:
        batch_op.drop_index('lrp_idx')

    op.drop_table('last_read_positions')
    op.drop_table('languages')
    op.drop_table('flask_settings')
    op.drop_table('feeds')
    op.drop_table('custom_columns')
    with op.batch_alter_table('conversion_options', schema=None) as batch_op:
        batch_op.drop_index('conversion_options_idx_b')
        batch_op.drop_index('conversion_options_idx_a')

    op.drop_table('conversion_options')
    op.drop_table('books_plugin_data')
    op.drop_table('books')
    op.drop_table('aws_credentials')
    op.drop_table('authors')
    op.drop_table('annotations_fts_stemmed_idx')
    op.drop_table('annotations_fts_stemmed_docsize')
    op.drop_table('annotations_fts_stemmed_data')
    op.drop_table('annotations_fts_stemmed_config')
    op.drop_table('annotations_fts_stemmed')
    op.drop_table('annotations_fts_idx')
    op.drop_table('annotations_fts_docsize')
    op.drop_table('annotations_fts_data')
    op.drop_table('annotations_fts_config')
    op.drop_table('annotations_fts')
    op.drop_table('annotations_dirtied')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index('annot_idx')

    op.drop_table('annotations')
    # ### end Alembic commands ###
