"""aws active colunm added

Revision ID: 7f39d67c8f17
Revises: 04f7fd038b41
Create Date: 2026-06-11 14:41:05.772656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f39d67c8f17'
down_revision = '04f7fd038b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_threads')
    op.drop_table('forum_categories')
    op.drop_table('forum_comments')
    op.drop_table('forum_emojis')
    op.drop_table('forum_comment_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_comment_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['forum_comments.id'], name=op.f('forum_comment_likes_comment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_comment_likes_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name=op.f('unique_user_comment_like'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('forum_emojis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('annotation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('group', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subgroup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hexcode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unicode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('directional', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('variation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('emoticons', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('shortcodes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('skintone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skintone_base', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skintone_combination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variation_base', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_emojis_pkey'))
    )
    op.create_table('forum_comments',
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['forum_comments.id'], name=op.f('forum_comments_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], name=op.f('forum_comments_thread_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_comments_pkey'))
    )
    op.create_table('forum_categories',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_categories_pkey')),
    sa.UniqueConstraint('slug', name=op.f('forum_categories_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('forum_threads',
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('best_comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['forum_categories.id'], name=op.f('forum_threads_category_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_threads_pkey')),
    sa.UniqueConstraint('book_id', name=op.f('forum_threads_book_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name=op.f('forum_threads_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
