"""check-autogenerate

Revision ID: f3c205af6c28
Revises: 7f39d67c8f17
Create Date: 2026-08-14 18:29:30.023200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c205af6c28'
down_revision = '7f39d67c8f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aws_access_key_id', sa.Text(), nullable=False),
    sa.Column('aws_secret_access_key', sa.Text(), nullable=False),
    sa.Column('default_region', sa.String(length=64), nullable=False),
    sa.Column('default_output_format', sa.String(length=16), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_credentials')
    # ### end Alembic commands ###
